# fly.toml app configuration file generated for blog-wujaag on 2026-09-02T07:17:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blog-wujaag'
primary_region = 'nrt'

[build]

[env]
  ADDRESS_HEADER = 'Fly-Client-IP'
  HOST = '0.0.0.0'
  HOST_HEADER = 'host'
  NODE_ENV = 'production'
  PORT = '3000'
  PROTOCOL_HEADER = 'x-forwarded-proto'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
