allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  core-js: false
  esbuild: true
  sharp: true
  svelte-preprocess: true

peerDependencyRules:
  allowedVersions:
    svelte-markdown>svelte: '5'
